services:
  app:
    build: .
    container_name: hellish-app
    restart: unless-stopped
    environment:
       MONGO_URL: ${MONGO_URL}
       BOT_TOKEN : ${BOT_TOKEN}
       ENCRYPTION_KEY : ${ENCRYPTION_KEY}
    depends_on:
      - mongo
    networks:
      - hellish-network
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo:/data/db
    networks:
      - hellish-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: ${ISBASIC_AUTH}
    networks:
      - hellish-network
    depends_on:
      - mongo

networks:
  hellish-network:
    driver: bridge

volumes:
  mongo:
    driver: local
